name: Latest blog post workflow
on: 
    schedule:
        # Run every hour - cron: '0 * * * *'
        - cron: '0 0 1 * *' # Runs at 00:00 every 1st of the month
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: gautamkrishnar/blog-post-workflow@master
              with: 
                max_post_count: "4"
                feed_list: "https://medium.com/feed/@kevin_huang_iim"
